version: '3.1'

services:

  db:
    image: mongo:4.4
    restart: always
    ports:
      - 54321:27017
    volumes:
      - ./db:/data/db
      - ./mongod.conf:/etc/mongod.conf.orig
    environment:
      MONGO_INITDB_ROOT_USERNAME: boostr
      MONGO_INITDB_ROOT_PASSWORD: boostr123